#INCLUDE <TV_PICKIT2_SHIFT_1.c>
#INCLUDE <MATH.H>
UNSIGNED INT8 J;
UNSIGNED INT16 KQADC;
FLOAT K_CACH;
VOID GIAI_MA_HIENTHI_4LED(FLOAT TAM)
{
   UNSIGNED INT16 X;
   X=(UNSIGNED INT16) TAM;
   XUAT_4LED_7DOAN_GIAIMA_XOA_SO0(X);
}

VOID MAIN()
{
   SET_UP_PORT_IC_CHOT();
   SETUP_ADC(ADC_CLOCK_DIV_32);
   SETUP_ADC_PORTS(AN0_TO_AN2|VSS_VDD);
   SET_ADC_CHANNEL(2);
   WHILE(TRUE)
   {
      KQADC=0;
      FOR(J=0;J<20;J++)
      {
         KQADC=KQADC+READ_ADC();
         DELAY_MS(10);
         K_CACH=POW(4277/KQADC,1.106);
         
         IF(KQADC>80)               K_CACH=80;
         GIAI_MA_HIENTHI_4LED(K_CACH);
      }
   }
}
